# This is an example of a schema file. Change it however you like.

type Post {
	title: String!
	description: String
	body: String
	coverImage: String
	author: User!
}

type User {
	name: String!
	email: String!
	avatar: String
}

input CreatePostInput {
	title: String!
	description: String
	body: String
	coverImage: String
}

type Mutation {
	createPost(input: CreatePostInput!): Post @resolver(name: "createPost")
}

type Query {
	posts: [Post]
	post(id: ID!): Post
}
